spring.application.name=ticket-price
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml


# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC URL for H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Username and password (set these according to your configuration)
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Pretty log output format
logbook.format.style=http

# Obfuscate sensitive headers (optional)
logbook.obfuscate.headers=Authorization

# Exclude paths from logging (e.g., Prometheus metrics, health checks)
logbook.exclude[0]=/actuator/**
logbook.include[0]=/api/**

logging.level.org.zalando.logbook=DEBUG
logging.level.org.springframework.web=DEBUG
